
#ifndef _SA_STATUS_CODE_
#define _SA_STATUS_CODE_


//sa application message notice dict
enum{
    SA_Shm_Init = 0,
    SA_ShmGetID_startflag,
    SA_ShmGetAddr_startflag,
    SA_ShmGetID_basctrl,
    SA_ShmGetAddr_basctrl,
    SA_ShmGetID_configsweep,
    SA_ShmGetAddr_configsweep,
    SA_ShmGetID_configmeasure,
    SA_ShmGetAddr_configmeasure,
    SA_ShmGetID_sweepdata,
    SA_ShmGetAddr_sweepdata,
    SA_ShmGetID_measuredata,
    SA_ShmGetAddr_measuredata,
    SA_ShmGetID_sync,
    SA_ShmGetAddr_sync,
    SA_ShmGetID_configupdate,
    SA_ShmGetAddr_configupdate,
    SA_ShmGetID_channelparam,
    SA_ShmGetAddr_channelparam,
    SA_ShmGetID_fftfircommonnum,
    SA_ShmGetAddr_fftfircommonnum,
    SA_ShmGetID_sweepnum,
    SA_ShmGetAddr_sweepnum,
    SA_ShmGetID_tempercalc,
    SA_ShmGetAddr_tempercalc,

    SA_Sweepinterrupt_Init,
    SA_MemMap_Init,
    SA_FreqCntInterrupt_Init,
    SA_Sm_syncHandle_Create,
    SA_Sm_syncHandle_Init,
    SA_Sm_guiHandle_Create,
    SA_Sm_guiHandle_Init,
    SA_Sm_sweepHandle_Create,
    SA_Sm_sweepHandle_Init,
    SA_FreqCount_Thread_Init,
    SA_MidMsg_Thread_Init,
    SA_DataAcq_Thread_Init,
    SA_Sweep_Thread_Init,
    SA_RF_Init,
    SA_FreqMode_Init,
    SA_CALCData_Load,
    SA_IF_ATTEN,
    SA_RF_Path,
    SA_ZEROFRE_SUPAMPAtten,
    SA_SECMEDFRE_Atten,
    SA_ZEROFRE_SUPPhase,
    SA_LOW_PREAtten,
    SA_LOW_FRONTGate,
    SA_HIGH_PREAtten,
    SA_HIGH_FRONTGate,
    SA_LO_Control,
    SA_RBW,
    SA_VBW,
    SA_DETECTORMode,
    SA_DATAPROMode,
    SA_SWPStart,
    SA_ZEROSPANFlag,
    SA_DOTSWPTime,
    SA_TOTALSWPTime,
    SA_DISPLAYNum,
    SA_DETECTORFlag,
    SA_DATAADDRClr,
    SA_FFTBUCKETNum,
    SA_FFTCALNum,
    SA_FFTDirection,
    SA_FFTVALIDSTANum,
    SA_FFTVALIDENDNum,
    SA_FFTDOTSWPTime,
    SA_BUCKETTRIGTime,
    SA_RBWVBWFIL_DELAYTime,
    SA_TRIGType,
    SA_TRIGDirect,
    SA_TRIGTIME,
    SA_VEDIOTRIGAmp,
    SA_TRIGPERTIME,
    SA_RFBURSTTRIGAmp,
    SA_LASTBand,
    SA_LOStep,
    SA_LOLastBandKeeptime,
    SA_SEGPoint,
    SA_SWPStop,
    SA_CHECKSegNum,
    SA_FIRBUcketTime,
    SA_GETSPECData,
    SA_FreqSeg,
    SA_SweepInterrupt_Start,
    SA_SweepInterrupt_Stop,
    SA_FSRGet_Start,
    SA_FSRGet_Stop,
    SA_GateSweep_Source,
    SA_GateSweep_Control,
    SA_GateSweep_ControlValue,
    SA_GateSweep_GateMethod,
    SA_GateSweep_SynSrc,
    SA_GateSweep_Gate,
    SA_GateSweep_GateDelay,
    SA_GateSweep_GateLength,
    SA_GateSweep_PreventStatus,
    SA_GateSweep_PreventTime,
    SA_GateSweep_Period,
    SA_GateSweep_PerTrig_SrcDelay,
    SA_GateSweep_PerTrig_PrvStatus,
    SA_GateSweep_PerTrig_PrvTime,
    SA_GateSweep_RFBurst_TrigLevl,


    SA_ShmGetID_noticecode,
    SA_ShmGetAddr_noticecode,
    SA_ShmGetID_bsavisi,
    SA_ShmGetAddr_bsavisi,

    SA_ZeroRestrainCalFile_Read,
    SA_ZeroRestrainCalFile_LengthMatch,
    SA_ZeroRestrainCalFile_Write,
    SA_ZeroRestrain_Init,

    SA_QssFile_Read,
    SA_BandInfoFile_Read,

    SA_PreStateFile_Write,
    SA_PreStateFile_Read,
    SA_PreStateFile_LengthMatch,
    SA_DefaultStateConfigFile_Write,
    SA_DefaultStateConfigFile_Read,
    SA_DefaultStateConfigFile_LengthMatch,
    SA_LastStateConfigFile_Write,
    SA_LastStateConfigFile_Read,
    SA_LastStateConfigFile_LengthMatch,
    SA_UserStateConfigFile_Write,
    SA_UserStateConfigFile_Read,
    SA_UserStateConfigFile_LengthMatch,
    SA_AppStateFile_Write,
    SA_AppStateFile_Read,
    SA_AppStateFile_Null,
    SA_AppStateFile_Judge,
    SA_AppStateAndDataFile_Write,
    SA_AppStateAndDataFile_Read,
    SA_AppStateAndDataFile_Null,
    SA_AppStateAndDataFile_Judge,

    SA_ChnlPower_BW_Set,
    SA_ACP_ChnlBW_Set,
    SA_ACP_ChnlSP_Set,
    SA_OccupiedBW_BW_Set,
    SA_OccupiedBW_XDB_Set,
    SA_SpecEMDisplay_Set,
    SA_SpecEMRefType_Set,
    SA_SpurReportType_Set,
    SA_SpurEMAveType_Set,
    SA_SpurEMTableType_Set,

    SA_CenterFreq_Set,
    SA_StartFreq_Set,
    SA_StopFreq_Set,
    SA_CFFreq_Set,
    SA_FreqOffset_Set,
    SA_Span_Set,
    SA_FullSpan_Set,
    SA_ZeroSpan_Set,
    SA_LastSpan_Set,

    SA_RefLevel_Set,
    SA_AttenValue_Set,
    SA_AttenStatus_Set,
    SA_ScaleDiv_Set,
    SA_AmpUnit_Set,
    SA_PreampStatus_Set,
    SA_RefOffset_Set,
    SA_AutoScale_Set,

    SA_AutoRbwStatus_Set,
    SA_AutoVbwStatus_Set,
    SA_VbwtoRbw_Set,

    SA_AutoSweepTimeStatus_Set,
    SA_AutoDotSweepTime_Set,
    SA_FixSweepMode_Set,
    SA_ZeroSpanTime_Set,

    SA_TriggerDelayStatus_Set,
    SA_TriggerSlope_Set,
    SA_TriggerLevel_Set,
    SA_TriggerPerTime_Set,

    SA_TraceSelect_Set,
    SA_TraceType_Set,
    SA_TraceViewStatus_Set,
    SA_MarkerSelect_Set,
    SA_MarkerNoiseStatus_Set,
    SA_MarkerFreqCountStatus_Set,
    SA_MarkerType_Set,
    SA_MarkerToCF_Set,
    SA_MarkerToCFStep_Set,
    SA_MarkerToStart_Set,
    SA_MarkerToStop_Set,

    SA_LimitFreq_Set,
    SA_LimitAmp_Set,
    SA_LimitData_Set,
    SA_LimitCurPointIndex_Set,
    SA_LimitSelect_Set,
    SA_LimitLineStatus_Set,
    SA_LimitEdge_Set,
    SA_LimitEdgeValue_Set,
    SA_LimitTestStatus_Set,
    SA_LimitType_Set,
    SA_InsertLimitRow_Set,
    SA_DeleteLimitRow_Set,
    SA_DeleteLimitOne_Set,
    SA_DeleteLimitAll_Set,
    SA_AutoLimit_Set,

    SA_CHStandard_Set,
    SA_CommuDirection_Set,
    SA_ChannelNumber_Set,
    SA_ChannelNumStep_Set,

    SA_IFOutput_Set,

    SA_GateSweepGateViewStatus_Set,
};

#endif

