obj-y += parser.o 
obj-y += parse.o     
obj-y += sentence.o  
obj-y += tok.o 
obj-y += context.o 
obj-y += generator.o 
obj-y += info.o 
obj-y += nmea_time.o  
obj-y += generate.o 
obj-y += gmath.o

