#ifndef GLOBALDEF_H
#define GLOBALDEF_H

enum ConfigureInfoType
{
    CONFIGURE_INFO_UNKNOW = 0,
    CONFIGURE_INFO_REPLACE_FILE,
    CONFIGURE_INFO_CONTAIN_PATH,
    CONFIGURE_INFO_FOLDER_TRANSFINITE,
    CONFIGURE_INFO_REPLACE_DIR,
    CONFIGURE_INFO_REMOVE_FILE,
    CONFIGURE_INFO_REMOVE_FAIL,
    CONFIGURE_INFO_ILLEGAL_NAME,
    CONFIGURE_INFO_EMPTY_NAME,
    CONFIGURE_INFO_MKDIR_FAIL,
    CONFIGURE_INFO_EXIST_NAME,
    CONFIGURE_INFO_USELESS_FILE,
    CONFIGURE_INFO_ILLEGAL_RENAME,
    CONFIGURE_INFO_EMPTY_RENAME,
    CONFIGURE_INFO_SAME_RENAME,
    CONFIGURE_INFO_EXSIT_RENAME,
    CONFIGURE_INFO_RENAME_FAIL,
    CONFIGURE_INFO_LOAD_USELESS,
    CONFIGURE_INFO_LOAD_DIR,
    CONFIGURE_INFO_ILLEGAL_SAVENAME,
    CONFIGURE_INFO_EXIST_SAVENAME,
    CONFIGURE_INFO_EMPTY_SAVENAME,
    CONFIGURE_INFO_WRONG_LOADTYPE,
    CONFIGURE_INFO_SAVE_FAIL,
    CONFIGURE_INFO_LOAD_FAIL,
};

#define TOP_DIR     "/app/UserData"
#define USB_TOP_DIR "/media/USB"
#define SD_TOP_DIR  "/media/SD"

#define TYPE_STATE "State"
#define TYPE_STATE_AND_DATA "State + Data"
#define TYPE_SCREEN_IMAGE "Screen Image"
#define TYPE_MEASURE_DATA "Measurement Data"
#define TYPE_LIMIT "Limit"

enum FILE_TYPE
{
    FILE_TYPE_NONE = 0,
    FILE_TYPE_STATE,
    FILE_TYPE_STATE_AND_DATA,
    FILE_TYPE_SCREEN_IMAGE,
    FILE_TYPE_MEASURE_DATA,
    FILE_TYPE_LIMIT,
};

enum MODULE_TYPE
{
    MODULE_TYPE_NONE = 0,
    MODULE_TYPE_RF,
    MODULE_TYPE_MODU,
    MODULE_TYPE_OTA,
    MODULE_TYPE_PVT,
    MODULE_TYPE_CAT,
    MODULE_TYPE_CCDF,
    MODULE_TYPE_AUTO,
    MODULE_TYPE_AUTOSAVE,
    MODULE_TYPE_BEAM,
    MODULE_TYPE_EIRP,
    MODULE_TYPE_ROUTEMAP
};

enum COMPONENT_TYPE
{
    COMP_TYPE_NONE = 0,
    COMP_TYPE_TDD,
    COMP_TYPE_FDD,
    COMP_TYPE_NR,
};

#endif // GLOBALDEF_H
