obj-y += unity.o 
obj-y += error_functions.o 
obj-y += Temp.o 
obj-y += FPGATemp.o 
obj-y += Touch.o 
obj-y += udisk.o  
obj-y += SysDev.o  
obj-y += sndwav_common.o
obj-y += sndfm_common.o
obj-y += wav_parser.o
obj-y += lplay.o
obj-y += bitReload.o
obj-y += nmealib/ 

